### ISSUE TITLE
Notifications for read/unread?

### ISSUE THREAD

**Issue by maiksd** [st3fan/dovecot-xaps-plugin#5]
Hi, I noticed that, since switching from Load to Push, the "new" badge at Mail.app will never go away when I read the new mail on another device.

Is there any way to push notifications for read/unread status changes as well?

**Comment by denisu** [comment]
It is possible for App Store apps to clear the badge and the notification center by sending an empty push notification. Someone needs to try If that also works for Mail.app.

**Comment by st3fan** [comment]
Sorry this is not possible. The notifications only tell the clients "Hey go check email". There is no concept of an Unread count.

**Comment by zero-one-devteam** [comment]
As far as I've read there is a dovecot plugin "notify" which maybe can be used as "wrapper". So other events like moving, changing read status etc. could trigger a push event. That would be perfect, because waiting 15 min (in worst case) to sync changes that have been made on other devices causes a lot of confusion (because people change their devices frequently ...). Unfortunatly I could not find a documentation for the notify plugin so for me it's quite unclear how to start ...

**Comment by freswa** [comment]
Fixed with #31. The client simply fetches all changes upon notification. So we send a (delayed and accumulated) notification for all kind of events now. The badge should be updated then as well.
